# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
# See: https://docs.readthedocs.com/platform/stable/build-customization.html
---
version: 2

mkdocs:
  configuration: .config/mkdocs.yaml

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    post_checkout:
      - mkdir -p $READTHEDOCS_REPOSITORY_PATH/input
      - cd $READTHEDOCS_REPOSITORY_PATH && find . -maxdepth 1 -not -name . -not -name input -exec mv {} input/ \;
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - cd $READTHEDOCS_REPOSITORY_PATH/input && UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cd $READTHEDOCS_REPOSITORY_PATH/input && python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file .config/mkdocs.yaml
